/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IWstMTRG, IWstMTRGInterface } from "../IWstMTRG";

const _abi = [
  {
    inputs: [],
    name: "stMTRGPerToken",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IWstMTRG__factory {
  static readonly abi = _abi;
  static createInterface(): IWstMTRGInterface {
    return new utils.Interface(_abi) as IWstMTRGInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWstMTRG {
    return new Contract(address, _abi, signerOrProvider) as IWstMTRG;
  }
}
