npx hardhat flatten ./contracts/Lens/CompoundLens.sol > ./verify/flatten/CompoundLens.sol
npx hardhat flatten ./contracts/Comptroller.sol > ./verify/flatten/Comptroller.sol
npx hardhat flatten ./contracts/FeedPriceOracle.sol > ./verify/flatten/FeedPriceOracle.sol
npx hardhat flatten ./contracts/UnderwriterAdmin.sol > ./verify/flatten/UnderwriterAdmin.sol
npx hardhat flatten ./contracts/UnderwriterProxy.sol > ./verify/flatten/UnderwriterProxy.sol
npx hardhat flatten ./contracts/Unitroller.sol > ./verify/flatten/Unitroller.sol
npx hardhat flatten ./contracts/WhitePaperInterestRateModel.sol > ./verify/flatten/WhitePaperInterestRateModel.sol
npx hardhat flatten ./contracts/CErc20Delegator.sol > ./verify/flatten/CErc20Delegator.sol
npx hardhat flatten ./contracts/CErc20Delegate.sol > ./verify/flatten/CErc20Delegate.sol
npx hardhat flatten ./contracts/suErc20Delegator.sol > ./verify/flatten/suErc20Delegator.sol
npx hardhat flatten ./contracts/suErc20Delegate.sol > ./verify/flatten/suErc20Delegate.sol
